
name: Terraform Pre-Prod

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        working-directory: Environment/Pre-Prod
        run: terraform init

      - name: Terraform Plan
        working-directory: Environment/Pre-Prod
        run: terraform plan

      - name: Terraform Apply
        working-directory: Environment/Pre-Prod
        run: terraform apply -auto-approve
